# Generated by Django 4.0.1 on 2022-01-25 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=30)),
                ('food_day_count', models.IntegerField()),
                ('foot_week_count', models.IntegerField()),
                ('foot_period', models.IntegerField()),
                ('food_start', models.DateField()),
                ('food_end', models.DateField()),
                ('shipping_method', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'subscription',
            },
        ),
    ]
